paths:
  raw: "data/raw"
  interim: "data/interim"
  processed: "data/processed"
  models: "models/artifacts"
  reports: "models/reports"

model:
  type: "xgboost"
  params:
    n_estimators: 400
    max_depth: 6
    learning_rate: 0.05
    subsample: 0.9
    colsample_bytree: 0.9
  target: "purchase_intent"

features:
  text_col: "review_text"
  numeric:
    - rating_overall
    - rating_seat
    - rating_food
    - rating_cabin_service
    - rating_punctuality
    - prior_trips_12m
    - advance_purchase_days
  categoricals:
    - route
    - cabin
    - loyalty_tier

simulation:
  scenarios:
    - name: "Seat comfort +0.5"
      change: {"rating_seat": 0.5}
    - name: "On-time +10pp"
      change: {"rating_punctuality": 1.0}
    - name: "Lounge voucher"
      change: {"perk_lounge_voucher": 1}
