name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt pytest
      - run: python -m src.train_model
      - run: python -m src.simulate
      - run: python -m src.evaluate
      - run: pytest -q
